name: 🐞 Bug Report
description: File a bug report.
labels: ['bug']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ❗ **Before you fill in this bug report template**
        Please search open/closed issues before submitting. The bug might be already known and fixed before.
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: Please describe the issue.
    validations:
      required: true
  - type: textarea
    id: expected-outcome
    attributes:
      label: What was the expected outcome?
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: What steps can be followed to reproduce the bug or issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. Scroll down to...
        4. See error when...
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: ℹ️ Additional Information.
      description: |
        You can provide here any additional information you might have like screenshots or links.
  - type: checkboxes
    attributes:
      label: Wave module
      description: In what module of Wave problem occured?
      options:
        - label: Core
        - label: React
        - label: Site (documentation)
        - label: Storybook
        - label: one of design-tokens
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: And which version of the module this problem affects?
      placeholder: e.g. Wave react 0.5.1 or Wave core 1.6.0
    validations:
      required: false
  - type: checkboxes
    id: operating-system
    attributes:
      label: What operating systems are you seeing the problem on?
      options:
        - label: Windows
        - label: macOS
        - label: Android
        - label: iOS
        - label: Other
    validations:
      required: false
  - type: checkboxes
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Microsoft Edge
        - label: Internet Explorer
        - label: Other
    validations:
      required: false
  - type: textarea
    id: environment-details
    attributes:
      label: Environment details
      description: Here you can provide further information about the OS, browser, binaries (node, yarn, npm etc.) versions.
    validations:
      required: false
