blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://wave.volue.com/
    about: Check out our docs before submitting an issue. An answer might be already there!
  - name: 💬 Discussions
    url: https://github.com/Volue/wave/discussions
    about: Ask questions, get help and give us some feedback here!
