blank_issues_enabled: false
contact_links:
  - name: Discussions 💬
    url: https://github.com/Volue/wave/discussions
    about: Ask questions, discuss features, give us some feedback here
  - name: Documentation 📚
    url: https://wave.volue.com/
    about: Check out the official doc
