name: New feature proposal
description: Propose a new component, pattern, foundation or documentation to add to the Wave Design System
title: "[Feature]: "
labels: ["New feature proposal", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Before you fill in this proposal template:**
        - If you are suggesting a change to a component, pattern or foundation that is already in the Wave Design System, please comment on its [GitHub discussion instead] (https://github.com/Wavedigital/design-system/discussions). You can get to the discussion using the direct link at the bottom of each page in the Design System.
        - If you are proposing something new, check the [Wave Design System community backlog](https://github.com/Wavedigital/design-system/projects/1) first. There may already be a proposal for something similar. You can add examples of your own evidence to an existing proposal.
  - type: textarea
    id: what
    attributes:
      label: What feature would you like to add to the Wave Design System?
      description: Give a brief description of the new feature you want to propose for the Design System. This could be a component, pattern or foundation, or new documentation for an existing feature.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why should this new feature be added to the Design System?
      description: |
        Explain why you think this feature or content should be added to the Wave Design System.
        - What evidence do you have that your Wave service needs it?
        - What evidence do you have that it meets the needs of the users of that service?
        - Have you checked if it's already in the Wave Design System?
        - Have you considered creating a new variant of an existing feature instead of something new?
    validations:
      required: true
  - type: textarea
    id: supporting-material
    attributes:
      label: Supporting material
      description: Include links to any examples, research, prototypes or code that support your proposal.
    validations:
      required: false
  - type: textarea
    id: contacts
    attributes:
      label: Contacts
      description: The Design System working group has a weekly meeting. We will invite you to one of these meetings to give a show and tell about your proposal and answer any questions. Please tell us who to invite to that meeting. We recommend involving at least your product manager, user researcher and designer.
    validations:
      required: false