name: Projects

on:
  issues:
    types: [opened]

jobs:
  add-to-project-to-column:
    name: Add issue to project to column
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'feature-request')
    steps:
      - uses: konradpabjan/actions-add-new-issue-to-column@v1.1
        with:
          action-token: '${{ secrets.ISSUE_TEMPLATES_TEST_TOKEN }}'
          project-url: 'https://github.com/users/michalandrzejczak/projects/1'
          column-name: 'Feature request'
