name: Projects

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Make project card from issue
        uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/users/michalandrzejczak/projects/1
          github-token: ${{ secrets.ISSUE_TEMPLATES_TEST_TOKEN }}
          labeled: feature-request
          label-operator: OR
      - name: Log issue info
        run: |
          echo "Issue first label: ${{ github.event.issue.labels[0].name }}"
      - name: Assign project card to column
        if: github.event.issue.labels[0].name == 'feature-request'
        uses: alex-page/github-project-automation-plus@v0.8.2
        with:
          project: issue-templates-test project
          column: Feature request
          repo-token: ${{ secrets.ISSUE_TEMPLATES_TEST_TOKEN }}
