name: Projects

on:
  issues:
    types: [opened]

jobs:
  add-to-project-to-column:
    name: Add issue to project to column
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'feature-request')
    steps:
    - name: Assign issues to project
      uses: technote-space/create-project-card-action@v1
      with:
        PROJECT: issue-templates-test project
        COLUMN: Feature request
        GITHUB_TOKEN: ${{ secrets.ISSUE_TEMPLATES_TEST_TOKEN }}
