name: Projects

on:
  issues:
    types: [opened]

jobs:
  add-to-project-to-column:
    name: Add issue to project to column
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'feature-request')
    steps:
    - name: add-new-issues-to-organization-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.ISSUE_TEMPLATES_TEST_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/users/michalandrzejczak/projects/1
        GITHUB_PROJECT_COLUMN_NAME: Feature request
