name: Projects

on:
  issues:
    types: [opened]

jobs:
  add-to-project-to-column:
    name: Add issue to project to column
    runs-on: ubuntu-latest
    steps:
      - name: Assign feature requests to project
        if: contains(github.event.issue.labels.*.name, 'feature-request')
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.ISSUE_TEMPLATES_TEST_TOKEN }}
          user: michalandrzejczak
          # organization: volue-org-name
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
      - name: Assign bugs to project
        if: contains(github.event.issue.labels.*.name, 'bug')
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.ISSUE_TEMPLATES_TEST_TOKEN }}
          user: michalandrzejczak
          # organization: volue-org-name
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: Dev Backlog # Target status
